### PR TITLE
Schema.org product structured data

### PR DESCRIPTION
**Pull request by Ezyweb-uk**
Proposed updates:
1) src\Microweber\Providers\CategoryManager.php - changed group_by field reference to fix sql unknown field error
2) src\Microweber\Utils\Adapters\Template\RenderHelpers\TemplateMetaTagsRenderer.php - added product data to meta array for structured data for product pages.
3) userfiles\templates\default\header.php - added structured data in head tags for product pages for Google Shopping.

### CODE REVIEW

**Comment by peter-mw** [comment]
hi Nick, thanks for the PR, we will make a separate module for it. You now made it work only for products, but we will make it work for other modules too

**Comment by peter-mw** [comment]
It must work with hooks, something like this 


```

event_bind('module.content.front.render', function ($data) {
    $json_arr = [];
    foreach ($data as $item) {
        if ($item['content_type'] !== 'product') {
            continue;
        }
        $p = [];
        $p['name'] = $item['title'];
        $p['description'] = $item['description'];
        $p['image'] = get_picture($item['id']);
        $p['sku'] = $item['url_api'];
        $p['offers'] = [
            'url' => $item['link'],
            'price' => $item['price'],
            'priceCurrency' => 'USD',
            'availability' => ($item['in_stock'] ? "https://schema.org/InStock" : "https://schema.org/OutOfStock"),
            'sku' => $item['url_api']
        ];

        $json_arr[] = $p;
        $context = \JsonLd\Context::create('product', $p);

        echo $context;
    }
});


```

**Comment by Ezyweb-uk** [comment]
Hi Peter, Great news! I just wanted this PR to start the conversation in the hope of getting the feature into your roadmap, maybe the PR can now be archived. 

Yes it needs to work with other content including breadcrumb lists.

**Comment by peter-mw** [comment]
Yes, closing this PR for now and making new repository for module 

https://github.com/microweber-modules/schema-org


send PR on the module repo if you wish

**Pull request closed without merging**
