### PR TITLE
More Cleanings

### PR DESCRIPTION
**Pull request by imanghafoori1**

### CODE REVIEW

**Comment by imanghafoori1** [comment]
One question, how you return a view from your controller ?
it seem that normal view() helper is not going to work

**Comment by peter-mw** [comment]
Hi, you can return the view as string or you can return it as response https://laravel.com/docs/5.4/responses like

```
$response = \Response::make('some html');
return $response;
```

**Comment by imanghafoori1** [comment]
ok but how to use the view() helper function to render a blade file ?!

**Comment by imanghafoori1** [comment]
What was wrong with __construct ? was it buggy or what ?!

**Comment by peter-mw** [comment]
here is some tutorial by @ash-rain http://microweber.com/docs/guides/modules_laravel.md  on blade views, i dont use blade views so i dont know much 


for __construct ... yes it was returning null instead of the $app object

**Comment by peter-mw** [comment]
thanks for the cleanings, 

don't waste time to cleanup, the code needs refactor and it will be totally cleaned up some day when major refactor is done :)

**Comment by imanghafoori1** [comment]
I do not see what you exactly mean...
What is your plan for refactoring your code?
Do you plan to rewrite it ? or refactor the current code ?

I generally start refactoring with the most obvious and easy ones...
then venture into more grand breaking ones like restructuring the classes and etc...

These clean ups are as starting point...

**Comment by peter-mw** [comment]
ok, continue if you wish, i will merge it, but i don't know if its just waste of your time 

code will be refactored and huge classes must be separated on smaller, etc  

for example this huge class https://github.com/microweber/microweber/blob/1.0.5/src/Microweber/Providers/ShopManager.php

is now less huge
https://github.com/microweber/microweber/blob/1.0.9/src/Microweber/Providers/ShopManager.php


and when the code is refactored all the formating and small stuff is fixed anyway

**Pull request merged**
