### PR TITLE
Calendar updates and 2 other files

### PR DESCRIPTION
**Pull request by nickwuk**
calendar/admin.php - removed am/pm to fixed invalid date with moment.js

calendar/config.php - changed some field types from text to string and char and removed sql comment

Providers/UserManager.php - proposed addition of wrapping password2 error with check on option form_show_password_confirmation.

functions/bootstrap.php - proposed change min Php version from 5.3.0 to 5.6.0 as required for Laravel

(For some reason my online base fork is 11 commits behind MW 1.0.8, I'm trying to work out why it's not updated via github desktop)

### CODE REVIEW

**Comment by nickwuk** [comment]
I've not tested the UserManager.php proposed update.

**Comment by peter-mw** [comment]
thanks, i merged it into 1.0.8

**Comment by nickwuk** [comment]
calendar/admin.php still seems to include the am/pm time format in the time select options; When retested date+time seems to save ok in the db but does not display correctly in admin event 'tooltip' or event edit popup.

In config.php I guess you decided to stick with the text fields rather than string/char definitions.

**Comment by peter-mw** [comment]
hi, the merge was from 100+ files :) i may missed it and used the file from prev version, can you open new PR

**Comment by nickwuk** [comment]
Sorry, my fork was not synchronised with upstream. I will sync it before opening a new PR.

**Pull request merged**
