### PR TITLE
Cookie notice updates

### PR DESCRIPTION
**Pull request by Ezyweb-uk**
Added Facebook Pixel and Mautic Tracking to cookie notice module,

### CODE REVIEW

**Comment by peter-mw** [comment]
hi @Ezyweb-uk , can you submit this pull request for the branch https://github.com/microweber/microweber/tree/1.2

**Comment by Ezyweb-uk** [comment]
Hi Peter, 
A
re we moving to 1.2 for all pull requests from now? 

Is there a planned release date for 1.2?

**Comment by peter-mw** [comment]
hi Nick , yes we are putting all new code in 1.2 until we release it. 

Release planned for November (hopefully)

**Comment by Ezyweb-uk** [comment]
@peter-mw I've updated admin.php to be compatible with 1.2 in the file below:
[admin.zip](https://github.com/microweber/microweber/files/5169924/admin.zip)

**Comment by peter-mw** [comment]
Something happened with the commit

It says i changed 259375 lines of code on the resolve conflict

Can you change it again and submit new pull request for 1.2

**Comment by Ezyweb-uk** [comment]
Sorry, I think I see what I did wrong. New PR in a moment.

**Pull request closed without merging**
